<?php

/**
 * @file
 * The module file for os2loop_flag_content.
 */

/**
 * Implements hook_mail().
 *
 * @see \Drupal\os2loop_flag_content\Helper\MailHelper::mail()
 */
function os2loop_flag_content_mail($key, &$message, $params) {
  Drupal::service('os2loop_flag_content.mail_helper')->mail($key, $message, $params);
}

/**
 * Implements hook_os2loop_settings_is_granted().
 *
 * @see \Drupal\os2loop_flag_content\Helper\Helper::isGranted()
 */
function os2loop_flag_content_os2loop_settings_is_granted(string $attribute, $object = NULL) {
  return Drupal::service('os2loop_flag_content.helper')->isGranted($attribute, $object);
}
