#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
bold=$(tput bold)
normal=$(tput sgr0)

number_of_images=${1:-8}

for ((i=1; i<=$number_of_images; i++)); do
  image_filename=$dir/$(printf "image-%03d.jpg" $i)
  logo_filename=$dir/$(printf "logo-%03d.png" $i)
  curl --silent https://lorempixel.com/800/600/ >| $image_filename
  # Convert to 512x512 png.
  convert $image_filename -extent 512x512 $logo_filename
  echo "$image_filename ($logo_filename)"
done
