<?php

/**
 * @file
 * Contains os2loop_question.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\os2loop_question\Helper\Helper;

/**
 * Implements hook_help().
 */
function os2loop_question_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the os2loop_question module.
    case 'help.question.os2loop_question':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OS2Loop question') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function os2loop_question_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  Drupal::service(Helper::class)->alterForm($form, $form_state, $form_id);
}
