<?php

/**
 * @file
 * Contains os2loop_section_page.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function os2loop_section_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the os2loop_section_page module.
    case 'help.page.os2loop_section_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OS2Loop Section page') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function os2loop_section_page_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_os2loop_section_page_edit_form' || $form_id == 'node_os2loop_section_page_form') {
    foreach ($form['os2loop_section_page_paragraph']['widget'] as $widget_key => $widget) {
      if (is_array($widget) && is_numeric($widget_key) && isset($widget['subform'])) {
        $form['os2loop_section_page_paragraph']['widget'][$widget_key]['subform']['os2loop_section_page_block']['widget'][0]['settings']['views_label_checkbox']['#access'] = FALSE;
        $form['os2loop_section_page_paragraph']['widget'][$widget_key]['subform']['os2loop_section_page_block']['widget'][0]['settings']['views_label_fieldset']['#access'] = FALSE;
        $form['os2loop_section_page_paragraph']['widget'][$widget_key]['subform']['os2loop_section_page_block']['widget'][0]['settings']['views_label_field']['#access'] = FALSE;
        $form['os2loop_section_page_paragraph']['widget'][$widget_key]['subform']['os2loop_section_page_block']['widget'][0]['settings']['label_display']['#access'] = FALSE;
        $form['os2loop_section_page_paragraph']['widget'][$widget_key]['subform']['os2loop_section_page_block']['widget'][0]['settings']['label']['#access'] = FALSE;
      }
    }
  }
}
