<?php

/**
 * @file
 * Contains os2loop_section_page.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function os2loop_section_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the os2loop_section_page module.
    case 'help.page.os2loop_section_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OS2Loop Section page') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 *
 * @see \Drupal\os2loop_section_page\Helper\FormHelper::alterForm()
 */
function os2loop_section_page_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // @todo We should use hook_event_dispatcher for this
  // https://www.drupal.org/project/hook_event_dispatcher/issues/3199174
  \Drupal::service('os2loop_section_page.form_helper')->alterForm($form, $form_state, $form_id);
}

/**
 * Implements hook_preprocess_node().
 *
 * @see \Drupal\os2loop_section_page\Helper\Helper::preprocessNode()
 */
function os2loop_section_page_preprocess_node(&$variables) {
  \Drupal::service('os2loop_section_page.helper')->preprocessNode($variables);
}
