<?php

/**
 * @file
 * Contains views_flag_refresh.module.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function views_flag_refresh_views_pre_render(ViewExecutable $view) {
  // Check AJAX option.
  if ($view->display_handler->getOption('use_ajax')) {
    $extenders = $view->getDisplay()->getExtenders();
    // Check Views Flag Refresh display extender.
    if (isset($extenders['views_flag_refresh'])) {
      $options = $extenders['views_flag_refresh']->options;

      // Check refreshing flags.
      if (!empty($options['flags'])) {
        $settings = [];
        foreach ($options['flags'] as $flag_id) {
          $settings[$flag_id][$view->id()][$view->current_display] = TRUE;
        }
        // Attach refresh script with settings.
        $view->element['#attached']['library'][] = 'views_flag_refresh/refresh_ajax';
        $view->element['#attached']['drupalSettings']['viewsFlagRefresh']['flags'] = $settings;
      }
    }
  }
}
