<?php

/**
 * @file
 * Contains os2loop_search_db.module.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\os2loop_search_db\Helper\Helper;
use Drupal\search_api\Query\QueryInterface;

/**
 * Implements hook_help().
 */
function os2loop_search_db_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the os2loop_search_db module.
    case 'help.page.os2loop_search_db':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OS2Loop Search DB') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_search_api_autocomplete_suggestions_alter().
 *
 * @see \Drupal\os2loop_search_db\Helper\Helper::alterSuggestions()
 */
function os2loop_search_db_search_api_autocomplete_suggestions_alter(array &$suggestions, array $alter_params) {
  Drupal::service(Helper::class)->alterSuggestions($suggestions, $alter_params);
}

/**
 * Implements hook_search_api_query_alter().
 */
function os2loop_search_db_search_api_query_alter(QueryInterface $query) {
  Drupal::service(Helper::class)->alterSearchApiQuery($query);
}

/**
 * Implements hook_block_access().
 *
 * @see Helper::blockAccess()
 */
function os2loop_search_db_block_access(Block $block, $operation, AccountInterface $account) {
  return Drupal::service(Helper::class)->blockAccess($block, $operation, $account);
}
