<?php

/**
 * @file
 * Hooks for OS2Loop Mail notifications.
 */

use Drupal\os2loop_mail_notifications\Helper\Helper;
use Drupal\os2loop_mail_notifications\Helper\MailHelper;

/**
 * Implements hook_cron().
 */
function os2loop_mail_notifications_cron() {
  Drupal::service(Helper::class)->cron();
}

/**
 * Implements hook_mail().
 */
function os2loop_mail_notifications_mail($key, &$message, $params) {
  Drupal::service(MailHelper::class)->mail($key, $message, $params);
}

/**
 * Implements hook_mail().
 */
function os2loop_mail_notifications_mail($key, &$message, $params) {
  Drupal::service('os2loop_mail_notifications.mail_helper')->mail($key, $message, $params);
}
