<?php

/**
 * @file
 * The module file for os2loop_media.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;
use Drupal\os2loop_media\Helper\Helper;

/**
 * Implements hook_views_query_alter().
 *
 * @see \Drupal\os2loop_media\Helper\Helper::queryAlter()
 */
function os2loop_media_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  Drupal::service(Helper::class)->queryAlter($view, $query);
}

/**
 * Implements hook_form_alter().
 *
 * @see \Drupal\os2loop_media\Helper\Helper::alterForm()
 */
function os2loop_media_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  Drupal::service(Helper::class)->alterForm($form, $form_state, $form_id);
}
