<?php

/**
 * @file
 * The module file for os2loop_upvote.
 */

/**
 * Use service to add number of upvotes to flag.
 */
function os2loop_upvote_preprocess_flag(array &$variables) {
  \Drupal::service('os2loop_upvote.flag_helper')->flagCounts($variables);
}

/**
 * Use service to find the top comment.
 */
function os2loop_upvote_preprocess_field(array &$variables, $hook) {
  \Drupal::service('os2loop_upvote.flag_helper')->preprocessFlag($variables);
}

/**
 * Add classes for styling.
 */
function os2loop_upvote_preprocess_comment(array &$variables) {
  if (isset($variables['elements']['#top'])) {
    // @todo when styling change these classes to fit.
    $variables['attributes'] += ['class' => ['top-comment']];
  }
}
