<?php

/**
 * @file
 * Enables modules and site configuration for a standard site installation.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;
use Drupal\os2loop_settings\Helper\Helper;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_create_access().
 *
 * @see \Drupal\os2loop_settings\Helper\Helper::entityCreateAccess()
 */
function os2loop_settings_entity_create_access(AccountInterface $account, array $context, $entity_bundle) {
  return Drupal::service(Helper::class)->entityCreateAccess($account, $context, $entity_bundle);
}

/**
 * Implements hook_node_access().
 *
 * @see \Drupal\os2loop_settings\Helper\Helper::nodeAccess()
 */
function os2loop_settings_node_access(NodeInterface $node, $op, AccountInterface $account) {
  return Drupal::service(Helper::class)->nodeAccess($node, $op, $account);
}

/**
 * Implements hook_form_alter().
 *
 * @see \Drupal\os2loop_settings\Helper\Helper::formAlter()
 */
function os2loop_settings_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  return Drupal::service(Helper::class)->formAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_preprocess_node().
 *
 * @see \Drupal\os2loop_settings\Helper\Helper::preprocessNode()
 */
function os2loop_settings_preprocess_node(array &$variables) {
  return Drupal::service(Helper::class)->preprocessNode($variables);
}

/**
 * Implements hook_preprocess_user().
 *
 * @see \Drupal\os2loop_settings\Helper\Helper::preprocessUser()
 */
function os2loop_settings_preprocess_user(array &$variables) {
  return Drupal::service(Helper::class)->preprocessUser($variables);
}
