<?php

/**
 * @file
 * Code for the Loop documents feature.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function os2loop_documents_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the os2loop_documents module.
    case 'help.documents.os2loop_documents':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OS2Loop documents') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 *
 * @see \Drupal\os2loop_documents\Helper\FormHelper::alterForm()
 */
function os2loop_documents_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // @todo We should use hook_event_dispatcher for this
  // https://www.drupal.org/project/hook_event_dispatcher/issues/3199174
  \Drupal::service('os2loop_documents.form_helper')->alterForm($form, $form_state, $form_id);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 *
 * @see \Drupal\os2loop_documents\Helper\NodeHelper::updateNode()
 */
function os2loop_documents_node_update(EntityInterface $entity) {
  \Drupal::service('os2loop_documents.node_helper')->updateNode($entity);
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @see \Drupal\os2loop_documents\Helper\NodeHelper::preprocessNode()
 */
function os2loop_documents_preprocess_node(array &$variables) {
  \Drupal::service('os2loop_documents.node_helper')->preprocessNode($variables);
}

/**
 * Implements hook_theme().
 *
 * @see \Drupal\os2loop_documents\Helper\NodeHelper::theme()
 */
function os2loop_documents_theme($existing, $type, $theme, $path) {
  return \Drupal::service('os2loop_documents.node_helper')->theme($existing, $type, $theme, $path);
}
