<?php

/**
 * @file
 * OS2loop subscriptions.
 */

/**
 * Implements hook_theme().
 *
 * Theme hook implementation for os2loop subscriptions.
 */
function os2loop_subscriptions_theme($existing, $type, $theme, $path) {
  return [
    'os2loop_subscriptions_user' => [
      'template' => 'os2loop-subscriptions-user',
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_os2loop_settings_is_granted().
 *
 * @see \Drupal\os2loop_subscriptions\Helper\Helper::isGranted()
 */
function os2loop_subscriptions_os2loop_settings_is_granted(string $attribute, $object = NULL): bool {
  return Drupal::service('os2loop_subscriptions.helper')->isGranted($attribute, $object);
}
