<?php

/**
 * @file
 * The module file for os2loop_share_with_a_friend.
 */

/**
 * Implements hook_mail().
 *
 * @see \Drupal\os2loop_share_with_a_friend\Helper\MailHelper::mail()
 */
function os2loop_share_with_a_friend_mail($key, &$message, $params) {
  Drupal::service('os2loop_share_with_a_friend.mail_helper')->mail($key, $message, $params);
}

/**
 * Implements hook_os2loop_settings_is_granted().
 *
 * @see \Drupal\os2loop_share_with_a_friend\Helper\Helper::isGranted()
 */
function os2loop_share_with_a_friend_os2loop_settings_is_granted(string $attribute, $object = NULL) {
  return Drupal::service('os2loop_share_with_a_friend.helper')->isGranted($attribute, $object);
}
