<?php

/**
 * @file
 * Code for the Os2loop cookie information module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * @see \Drupal\os2loop_cookie_information\Helper\FormHelper::alterForm()
 */
function os2loop_cookie_information_form_os2loop_cookies_settings_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  \Drupal::service('os2loop_cookie_information.form_helper')->alterForm($form, $form_state, $form_id);
}
